### ISSUE TITLE
Use LoadBalancer for Istio gateway for Docker for Desktop installs

### ISSUE THREAD

**Issue by trisberg** [projectriff/projectriff.io#172]
For Docker for Desktop I typically install the primary ingress controller with LoadBalancer since that seems to work fine and the service can be accessed on localhost at port 80 and I can add entries in /etc/hosts for my deployed knative services. This only works for a single LoadBalancer though, so not sure if we want to rely ion that for these instructions.

**Comment by scothis** [comment]
If it doesn't work reliably, we shouldn't recommend it

**Comment by trisberg** [comment]
It seems reliable if you limit it to one service. Without relying on this how could you add the host for a service to `/etc/hosts` which is something we need for our demo?

**Comment by scothis** [comment]
> It seems reliable if you limit it to one service.

There's no guarantee that there won't be another LoadBalancer in the cluster, Especially in an environment like Docker Desktop where you can only have a single cluster.

> Without relying on this how could you add the host for a service to /etc/hosts which is something we need for our demo?

Since we're exposing a single remote port, the main difference between a LoadBalancer and NodePort is the port number listening for traffic. With NodePort that port number will be something high, and not 80. 

DNS resolution is orthogonal. One can either publish public DNS records, or use a service like xip.io, or locally override their DNS resolver.

**Comment by trisberg** [comment]
That works for curl but doesn't really work with apps, e.g. the demo storefront, that you want to access using a browser. Seems providing the host header is necessary for the routing to work so you can't just open the url in the browser.
